spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Local instance MySQL80?serverTimezone=UTC
    username: root
    password: Kristel123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.yourmailhost.com
    port: 587
    username: your_email@example.com
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

jwt:
  secret: mySuperSecretKeyChangeThis
  expiration: 3600000 # 1 hour in ms
